name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  #### Java
  build-test-java:
    name: Build Java Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up Java
        uses: actions/setup-java@8f12c5c4d1ebd18bf4b7a51a1b0b912633f0bc61
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Java packages
        uses: actions/cache@2b5a782c6414f96354f95902141714b127692d1e
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-v1
          restore-keys: ${{ runner.os }}-m2-
      - name: Build
        run: |
          mvn -U compile

  release-test-deploy:
    needs: build-test-java
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up Maven Central Repository
        uses: actions/setup-java@8f12c5c4d1ebd18bf4b7a51a1b0b912633f0bc61
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
#      - name: Cache Java packages
#        uses: actions/cache@2b5a782c6414f96354f95902141714b127692d1e
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-v1
#          restore-keys: ${{ runner.os }}-m2-
      - name: Publish
        run: |
          mvn -DskipTests deploy -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
